NORMAL_AXE_KNOCKBACK_POWER = 10
NORMAL_AXE_SIZE = 24
NORMAL_AXE_COOLDOWN = 20
NORMAL_AXE_SWING_ANGLE = 90
NORMAL_AXE_SWING_ATTACK_RANGE = 12
NORMAL_AXE_SWING_DURATION = 10

NORMAL_AXE_ACTIVE_LIFE = 1
NORMAL_AXE_SWING_DAMAGE = 1
NORMAL_AXE_THROW_DAMAGE = 2
NORMAL_AXE_THROW_DURATION = 10
NORMAL_AXE_MIN_THROW_SPEED = 6
NORMAL_AXE_MAX_THROW_POWER = 20
