POISION_BOMB_TICK_DAMAGE = 1
POISION_BOMB_EXPLOSION_SIZE = 48
POISION_BOMB_MIN_THROW_RANGE = 64
POISION_BOMB_MAX_THROW_RANGE = 256
POISION_BOMB_HITTING_COOLDOWN = 5
POISION_BOMB_DELAY_COOLDOWN = 30
POISION_BOMB_ACTIVE_DURATION = 20


FIRE_BOMB_TICK_DAMAGE = 2
FIRE_BOMB_EXPLOSION_SIZE = 32
FIRE_BOMB_MIN_THROW_RANGE = 128
FIRE_BOMB_MAX_THROW_RANGE = 320
FIRE_BOMB_HITTING_COOLDOWN = 8
FIRE_BOMB_DELAY_COOLDOWN = 20
FIRE_BOMB_ACTIVE_DURATION = 40
