import math
NORMAL_AXE_ATTACK_RANGE = 12
NORMAL_AXE_SIZE = 24
NORMAL_AXE_DURATION = 10
NORMAL_AXE_COOLDOWN = 20
NORMAL_AXE_SWING_ANGLE = 90
NORMAL_AXE_LIFE = 1
NORMAL_AXE_DAMAGE = 1

NORMAL_STONE_TARGETING_RANGE = 160
NORMAL_STONE_TARGETING_ANGLE = 45  # degree
NORMAL_STONE_DAMAGE = 1
NORMAL_STONE_LIFE = 1
NORMAL_STONE_SIZE = 16
NORMAL_STONE_MIN_SPEED = 6
NORMAL_STONE_MAX_POWER = 10
NORMAL_STONE_DURATION = 10
NORMAL_STONE_COOLDOWN = 30
