NORMAL_AXE_ATTACK_RANGE = 12
NORMAL_AXE_SIZE = 24
NORMAL_AXE_DURATION = 10
NORMAL_AXE_COOLDOWN = 20
NORMAL_AXE_SWING_ANGLE = 90
NORMAL_AXE_LIFE = 1
NORMAL_AXE_DAMAGE = 1

NORMAL_STONE_DAMAGE = 1
NORMAL_STONE_LIFE = 1
NORMAL_STONE_SIZE = 16
NORMAL_STONE_SPEED = 8
NORMAL_STONE_ATTACK_RANGE = 128
NORMAL_STONE_COOLDOWN = 30
